App\Entity\Location:
    properties:
        city:
            - NotBlank: { groups: ['create', 'edit'], message: 'City cannot be blank.' }
            - Length:
                  min: 2
                  max: 50
                  minMessage: 'City name must be at least {{ limit }} characters long.'
                  maxMessage: 'City name cannot be longer than {{ limit }} characters.'
                  groups: ['create', 'edit']
        country:
            - NotBlank: { groups: ['create', 'edit'], message: 'Country cannot be blank.' }
        latitude:
            -   NotBlank: { groups: [ 'create', 'edit' ], message: 'Latitude cannot be blank.' }
            -   Range: { min: -90, max: 90, notInRangeMessage: 'Latitude must be between {{ min }} and {{ max }}.', groups: [ 'create', 'edit' ] }
        longitude:
            -   NotBlank: { groups: [ 'create', 'edit' ], message: 'Longitude cannot be blank.' }
            -   Range: { min: -180, max: 180, notInRangeMessage: 'Longitude must be between {{ min }} and {{ max }}.', groups: [ 'create', 'edit' ] }

